export const TYPE = 'HERO';

export const ACTIONS = {
  FETCH_ALL_START: `${TYPE}/FETCH_ALL/START`,
  FETCH_ALL_ERROR: `${TYPE}/FETCH_ALL/ERROR`,
  FETCH_ALL_SUCCESS: `${TYPE}/FETCH_ALL/SUCCESS`,

  FETCH_ALL: `${TYPE}/FETCH_ALL`,
};
